stages:
  - test
  - build
run_tests:
  stage: test
  image: python:3.10-buster
  services:
    - postgres:14.3
  variables:
    DJANGO_SETTINGS_MODULE: todo.settings
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_HOST_AUTH_METHOD: trust
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - python -V
    - pip install -r requirements.txt
  script:
    - env
    - cd src
    - python -m pytest
build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMG_NAME: spino13/todo
    IMG_TAG: v1.0
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  script:
    - docker buildx build --platform linux/amd64,linux/arm64 -t $IMG_NAME:$IMG_TAG .
    - docker push $IMG_NAME:$IMG_TAG

