run_tests:
  image: python:3.10-buster
  services:
    - postgres:12.2-alpine
  variables:
    DJANGO_SETTINGS_MODULE: todo.settings
    SECRET_KEY: $SECRET_KEY
    POSTGRES_DB: "todo"
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "admin"
    POSTGRES_HOST_AUTH_METHOD: trust

  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - python -V
    - pip install -r requirements.txt
  script:
    - cd src
    - python -m pytest
