run_tests:
  image: python:3.10-buster
  services:
    - postgres:14.3
  variables:
    DJANGO_SETTINGS_MODULE: todo.settings
    SECRET_KEY: $SECRET_KEY
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_HOST_AUTH_METHOD: trust

  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - python -V
    - pip install -r requirements.txt
  script:
    - env
    - cd src
    - python -m pytest
