# Generated by Django 4.0.6 on 2022-07-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True, max_length=125)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('favorite', models.BooleanField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='lists.list')),
            ],
        ),
    ]
